## Takes in data generated by data_load
## Calculates missing data, complete data profile and cardinality(Different values for columns. Ex - Card Type-Visa/Master/Amex, Cardinality=3

from pathlib import Path
import json
import pandas as pd


class DataProfiler:

    def __init__(self, df):
        self.df = df

    def generate_reports(self):

        report_dir = Path("reports")
        report_dir.mkdir(parents=True, exist_ok=True)

        # Missing values
        missing = (
            self.df.isnull()
            .mean()
            .sort_values(ascending=False)
            * 100
        )

        missing.to_csv(
            report_dir / "missing_values.csv"
        )

        # Cardinality
        cat_cols = self.df.select_dtypes(
            include=["object"]
        ).columns

        cardinality = {
            col: self.df[col].nunique()
            for col in cat_cols
        }

        pd.Series(cardinality).to_csv(
            report_dir / "cardinality.csv"
        )

        # Target distribution
        target_pct = (
            self.df["isFraud"]
            .value_counts(normalize=True)
            .to_dict()
        )

        summary = {
            "num_rows": len(self.df),
            "num_columns": len(self.df.columns),
            "fraud_distribution": target_pct
        }

        with open(
            report_dir / "profile_summary.json",
            "w"
        ) as f:
            json.dump(summary, f, indent=4)

        print("Profiling reports generated.")