## Loads the interim daataset generated by load_data
## Drops columns which have >95% data (rows) empty
## Removes leakage column, in this case TransactionID
## Label encoding all the object columns (0,1,2.....)
## Imputes missing values in columns with median
## Splits features and creates target target = "isFraud"

import json
from pathlib import Path

import pandas as pd
import yaml
from sklearn.preprocessing import LabelEncoder


class FeatureBuilder:

    def __init__(
            self,
            config_path: str = "configs/config.yaml",
            params_path: str = "params.yaml"
    ):
        self.config = self._load_yaml(config_path)
        self.params = self._load_yaml(params_path)

    @staticmethod
    def _load_yaml(path):

        with open(path, "r") as file:
            return yaml.safe_load(file)

    def load_dataset(self):

        input_path = self.config["data"]["interim_dataset"]

        return pd.read_parquet(input_path)

    def drop_high_missing_columns(self, df):

        threshold = self.params["feature_engineering"][
            "missing_threshold"
        ]

        missing_ratio = df.isnull().mean()

        columns_to_drop = (
            missing_ratio[
                missing_ratio > threshold
                ].index.tolist()
        )

        df = df.drop(columns=columns_to_drop)

        return df, columns_to_drop

    @staticmethod
    def drop_leakage_columns(df):

        leakage_columns = [
            "TransactionID"
        ]

        existing_columns = [
            col
            for col in leakage_columns
            if col in df.columns
        ]

        df = df.drop(columns=existing_columns)

        return df, existing_columns

    @staticmethod
    def impute_missing_values(df):

        numeric_columns = df.select_dtypes(
            include=["number"]
        ).columns

        categorical_columns = df.select_dtypes(
            include=["object"]
        ).columns

        for col in numeric_columns:

            if col == "isFraud":
                continue

            median_value = df[col].median()

            df[col] = df[col].fillna(
                median_value
            )

        for col in categorical_columns:

            df[col] = df[col].fillna(
                "UNKNOWN"
            )

        return df

    @staticmethod
    def encode_categorical_features(df):

        categorical_columns = df.select_dtypes(
            include=["object"]
        ).columns

        label_encoders = {}

        for col in categorical_columns:

            encoder = LabelEncoder()

            df[col] = encoder.fit_transform(
                df[col].astype(str)
            )

            label_encoders[col] = (
                encoder.classes_.tolist()
            )

        return df, label_encoders

    @staticmethod
    def create_metadata(
            df,
            dropped_columns,
            leakage_columns,
            label_encoders
    ):

        categorical_features = list(
            label_encoders.keys()
        )

        metadata = {

            "num_rows": int(df.shape[0]),

            "num_features": int(
                len(df.columns) - 1
            ),

            "target_column": "isFraud",

            "categorical_features":
                categorical_features,

            "numeric_features": [
                col
                for col in df.columns
                if col not in categorical_features
                and col != "isFraud"
            ],

            "dropped_missing_columns":
                dropped_columns,

            "dropped_leakage_columns":
                leakage_columns
        }

        return metadata

    @staticmethod
    def save_metadata(metadata):

        output_path = Path(
            "artifacts/feature_metadata.json"
        )

        output_path.parent.mkdir(
            parents=True,
            exist_ok=True
        )

        with open(output_path, "w") as file:

            json.dump(
                metadata,
                file,
                indent=4
            )

    @staticmethod
    def save_dataset(df):

        output_path = Path(
            "data/processed/features.parquet"
        )

        output_path.parent.mkdir(
            parents=True,
            exist_ok=True
        )

        df.to_parquet(
            output_path,
            index=False
        )

    def build_features(self):

        print("Loading dataset...")

        df = self.load_dataset()

        print(
            f"Initial Shape: {df.shape}"
        )

        df, dropped_columns = (
            self.drop_high_missing_columns(df)
        )

        print(
            f"Dropped {len(dropped_columns)} "
            f"high-missing columns"
        )

        df, leakage_columns = (
            self.drop_leakage_columns(df)
        )

        print(
            f"Dropped {len(leakage_columns)} "
            f"leakage columns"
        )

        df = self.impute_missing_values(df)

        df, label_encoders = (
            self.encode_categorical_features(df)
        )

        metadata = self.create_metadata(
            df,
            dropped_columns,
            leakage_columns,
            label_encoders
        )

        self.save_metadata(metadata)

        self.save_dataset(df)

        print(
            f"Final Shape: {df.shape}"
        )

        print(
            "Feature engineering completed."
        )